version: '2.0'
services:
  gewe:
    image: registry.cn-hangzhou.aliyuncs.com/gewe/gewe:latest
    container_name: gewe
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - ../gewechat/temp:/root/temp
    privileged: true
    restart: always
    command: /usr/sbin/init
    networks:
      difywechat_network:
        ipv4_address: 172.33.0.32

  chatgpt-on-gewechat:
    image: crpi-xcrdbvalz21m1xhf.cn-beijing.personal.cr.aliyuncs.com/oneszhang/chatgpt-on-gewechat:v1.7.3
    container_name: chatgpt-on-gewechat
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - "7860:7860"
      - "9919:9919" # gewechat 回调服务端口
    volumes:
      - ../config.json:/app/config.json
      - ../plugins:/app/plugins
    privileged: true
    networks:
      difywechat_network:
        ipv4_address: 172.33.0.33

networks:
  difywechat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
